### ISSUE TITLE
don't commit without PR

### ISSUE THREAD

**Issue by MithrilMan** [block-core/blockcore#290]
Since this project become to be quite used, I think it should enforce some behavior like preventing straight commits (even if simple ones) without having a proper PR

Actually this commit https://github.com/block-core/blockcore/commit/e57dfdeade7b2d23b6628720e4a865eb6d87ae6d is breaking compatibility (e.g. I had a simple testing project where I was using Nuget package version 1.0.16 tha was .Net 5 and now I can't update the version because 1.0.17 has been rolled back to 3.1

What do you think if we commit just by proper PR? (straight commit can't even be commented)

**Comment by sondreb** [comment]
I think we should have a guideline that says PRs are preferred, but shouldn't be enforced on the repo.

Changes such as bumping version numbers, fixing small minor GitHub Actions errors, etc. shouldn't go through PRs. That will only pollute the PR history. PRs are for code changes that are open for reviews and reviews are wanted. It also gives us a nice history to go back to when needed.

The commit in question is reverting a major upgrade that was never released. We have never published any released using .NET 5. So I don't think that is the real problem you had?

Here is a good example on non-PR commit that is fine:

https://github.com/block-core/blockcore/commit/b8d16e9dff5c679ec1946f479db455ebe90c7fd9

From time to time, there might be commits that should have been PRs. We should of course try to avoid that, but I don't think we should enforce such a rule.

**Comment by MithrilMan** [comment]
I don't think that any commit should be considered as "minor" in the sense that any reason for a change should be documented stating why it has been changed

following code changes without PR is just a mess (by experience) when you want to understand why some code has been changed over time (there is no way to comment commits)

**Comment by MithrilMan** [comment]
I'm not saying that every PR should need full reviews maybe, so simple PR could have some tag that prevent full reviews (not sure if it's possible) but at least should the change reason should be commented

**Comment by sondreb** [comment]
The policy has already been on since we started, it's just that administrator have access directly. The change you would want then is for administrators to not be allowed direct commits. Think we should rather just say that all commits should be PR then and attempt that and see if it works fine, even for the smallest ones. I think the most important thing for smaller projects it to avoid ceremony and hurdles that increase threshold for rapid commits. The larger a project becomes and more contributors, the more important PRs become. Projects where we have mostly a single contributors, should not enforce PRs, in my opinion.

![image](https://user-images.githubusercontent.com/309938/110252726-0ec47280-7f87-11eb-911b-f7c34d681526.png)

**Comment by dangershony** [comment]
We mostly don't commit without PRs on rare occasions we do but yeah agree should try to avoid it

**Comment by sondreb** [comment]
We'll continue to leave it possible for admins to commit directly, in practice all commits since this was raised, has now been done with PRs.
