### ISSUE TITLE
Mnemonic wallet recovery does not discover cold/hot-balance 

### ISSUE THREAD

**Issue by viscolex** [block-core/blockcore#9]
When recovering a wallet using the mnemonic 12 words, only walletName/account0 gets discovered. 

walletName/coldStakingColdAddresses and walletName/coldStakingHotAddresses are not discovered, thus showing no balances and to the user it looks as if they were never set-up before.

Enabling Hot-Staking or Cold-Staking on a newly recovered wallet does not discover the previously used address either. Rescan and full datadir wipe does not help.

Looking at the recovered wallet.json file and comparing it against the original file, we can see that there is no data on the Internal Addresses starting `"index": 10000000;`
![Screenshot_635](https://user-images.githubusercontent.com/37867692/68037024-c45e2200-fcbe-11e9-911f-5772f7892392.png)

The only way to safely back-up your cold-staking balance or hot staking wallet is to regularly make a copy of the *.wallet.json, which really defeats the purpose of having a mnemonic recovery.

**Comment by dangershony** [comment]
I want to clarify the coins are not lost just not visible to the wallet, using custom technices one can recover the funds.

Is the above true also when recovering a hot wallet?

**Comment by thecrypt0hunter** [comment]
@dangershony confirmed the above is true for hot wallet.

**Comment by dangershony** [comment]
I believe the problem is that the wallet tracks the entire cold stake script(that includes the hot and cold key), to recover the cold script an external key is needed (cold/hot depends on what is being recovered)

A work around could be to track the key itself, but this means checking each script that comes in to the wallet if it's a CS script then extract the hot/cold key and match that key to a wallet key.
